### Load in NumPy (remember to pip install numpy first) This ntebook has been edited by me for practice purposes.

In [1]:
import numpy as np

### The Basics

In [15]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [8]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [9]:
# Get Dimension
a.ndim
b.ndim

2

In [11]:
# Get Shape
b.shape
a.shape

(3,)

In [22]:
# Get Type
a.dtype
b.dtype

dtype('float64')

In [21]:
# Get Size
a.itemsize
b.itemsize


8

In [23]:
# Get total size
a.nbytes
a.size*a.itemsize

12

In [18]:
# Get number of elements
b.size

6

### Accessing/Changing specific elements, rows, columns, etc

In [27]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [31]:
# Get a specific element [r, c]
a[1, 5]
a[1, 0]
a[1, -0]
a[1, -2]

13

In [15]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [32]:
# Get a specific column
a[:, 2]
a[:, -2]

array([ 6, 13])

In [39]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]
a[0, 1:-1:1]
a[0, 0:7:1]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [42]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


*3-d example

In [51]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [44]:
# Get specific element (work outside in)
b[0,1,1]

4

In [52]:
# replace 
#b[:,1,:] = [[9,9],[8,8]]
b[:,0,:] = [[9,9],[8,8]]
print(b)

[[[9 9]
  [3 4]]

 [[8 8]
  [7 8]]]


In [33]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initializing Different Types of Arrays

In [40]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [53]:
# All 1s matrix
#np.ones((4,2,2), dtype='int32')
np.ones((4,3,2), dtype='int32')

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]])

In [54]:
# Any other number
np.full((3,2,3), 9.4)

array([[[9.4, 9.4, 9.4],
        [9.4, 9.4, 9.4]],

       [[9.4, 9.4, 9.4],
        [9.4, 9.4, 9.4]],

       [[9.4, 9.4, 9.4],
        [9.4, 9.4, 9.4]]])

In [49]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [55]:
# Random decimal numbers
np.random.rand(3,2,3)

array([[[0.72897798, 0.96428917, 0.92364434],
        [0.14532587, 0.85341122, 0.48498807]],

       [[0.88529782, 0.39216939, 0.35050068],
        [0.99738782, 0.36857208, 0.16645996]],

       [[0.65765321, 0.43605071, 0.80512548],
        [0.80070927, 0.40909001, 0.55877638]]])

In [56]:
# Random Integer values
np.random.randint(-50,50, size=(4,2,3))

array([[[ 34, -45, -29],
        [ 45,  31, -42]],

       [[-14, -46, -31],
        [  0,   2,  30]],

       [[  4, -28,  -5],
        [-32, -21,   5]],

       [[-44,  -9, -47],
        [-40,  43,  36]]])

In [57]:
# The identity matrix
np.identity(5)
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [82]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [58]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

#output[1:-1,1:-1] = z
output[1:-1,0:-2] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [0. 0. 0. 1. 1.]
 [0. 9. 0. 1. 1.]
 [0. 0. 0. 1. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!

In [60]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)
print(b)

[1 2 3]
[100   2   3]


### Mathematics

In [61]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [63]:
a + 4

array([5, 6, 7, 8])

In [64]:
a - 4

array([-3, -2, -1,  0])

In [65]:
a * 2

array([2, 4, 6, 8])

In [104]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [118]:
b = np.array([1,0,1,0])
a + b

array([1, 0, 3, 0])

In [113]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [69]:
# Take the sin
print(np.cos(a))
print(np.sin(a))
print(np.tan(a))


[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128]


In [117]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

##### Linear Algebra

In [127]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [132]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [133]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

##### Statistics

In [70]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
print(np.min(stats))
print(np.min(stats,axis=0))
print(np.min(stats,axis=1))


1
[1 2 3]
[1 4]


In [76]:
print(np.max(stats, axis=1))
print(np.max(stats, axis=0))

[3 6]
[4 5 6]


In [77]:
print(np.sum(stats, axis=0))
print(np.sum(stats, axis=1))

[5 7 9]
[ 6 15]


### Reorganizing Arrays

In [83]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

#after = before.reshape((2,3))
#after = before.reshape((8,1))
#after = before.reshape((4,2))
after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [84]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [86]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

#np.hstack((h1,h2))
np.hstack([v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8])

### Miscellaneous
##### Load Data from File

In [179]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


##### Boolean Masking and Advanced Indexing

In [196]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])